### ISSUE TITLE
Highlight the voted numbers with a count

### ISSUE THREAD

**Issue by clemcodes** [AND-Digital-Jemison/story-estimator#23]
GIVEN all user have voted,
WHEN the reveal button is clicked,
THEN highlights the voted numbers with a count 
and THEN set the highest / most selected number in a readonly section
and THEN I can change the number by clicking the selection area point

**Comment by clemcodes** [comment]
//TODO

- [x]   1. fix issue with count pushing down card (translate issue)
- [x]   2. fix card color issue
- [x]   3. do not display votes count if zero for given card
- [x]   4. implement color red for MAX voted card.

**Comment by imran3** [comment]
point 4: some issue with counting max voted if all vote different cards ...
